[WEBSOCKET]
port = 7890

[VOTING]
VOTING_DURATION = 15
EFFECT_DURATION = 15

[TWITCH]
CHANNEL = "IncognitusAU"
TMI_TOKEN = "oauth:ad66pjmjvu9kbku98oa7uyq6fu45jd"

[GUI]
STAY_ON_TOP = false
THEME = "dark"

[GAME_CONFIGS]
dark_souls_remastered = "game_effects/DSR.toml"
dark_souls_ii = "game_effects/DS2.toml"
