[STAT_EFFECTS.one_hp]
enabled = false
channel_point_alias = ""

[SETTINGS_EFFECTS.lower_draw_distance]
enabled = false
channel_point_alias = ""

[SETTINGS_EFFECTS.blind]
enabled = false
channel_point_alias = ""

[GUI_EFFECTS.disable_hud]
enabled = false
channel_point_alias = ""

[HEAD_EFFECTS.big_head]
enabled = true
channel_point_alias = ""

[HEAD_EFFECTS.tiny_head]
enabled = true
channel_point_alias = ""

[BODY_EFFECTS.big_arm]
enabled = true
channel_point_alias = ""

[ACTION_EFFECTS.sliding]
enabled = false
channel_point_alias = ""

[ACTION_EFFECTS.warp_to_bonfire]
enabled = false
channel_point_alias = ""
